---
- hosts: dbservers
  sudo: yes
  tags: basic-install
  roles:
    - common
  handlers:
    - include: roles/handlers/main.yml


- hosts: masterNode
  sudo: yes
  tags: masterNode
  roles:
    - masterNode
  handlers:
    - include: roles/handlers/main.yml


- hosts: slaveNode
  sudo: yes
  tags: slaveNode
  roles:
    - slaveNode
  handlers:
    - include: roles/handlers/main.yml


- hosts: pgpoolm
  sudo: yes
  tags: pgpool-test
  roles:
    - pgpoolm
