---
- name: Allow user repuser r/w replication db
  lineinfile:
    path: /var/lib/pgsql/9.5/data/pg_hba.conf
    line: "{{ item }}"
    insertafter: EOF
    state: present
  with_items:
    - host    repmgr          repmgr      0.0.0.0/0           trust
    - host    replication     repmgr      0.0.0.0/0           trust
    - host    all             pgpool      0.0.0.0/0           trust
    - host    all             all         0.0.0.0/0           md5
  notify:
  - restart postgresql-9.5

- name: Allow user repuser r/w replication db
  lineinfile:
    insertafter: EOF
    state: present
    path: /var/lib/pgsql/9.5/data/postgresql.conf
    line: "{{ item }}"
  with_items:
    - max_wal_senders = 8
    - wal_level = 'hot_standby'
    - hot_standby = on
    - archive_mode = on
    - archive_command = '/bin/true'
  notify:
  - restart postgresql-9.5

- name: Create DB replication user
  become_user: postgres
  become: yes
  postgresql_user:
    name: repmgr
    encrypted: yes
    password: secret
    role_attr_flags: SUPERUSER # needs for repmgr
    state: present
  notify: restart postgresql-9.5

- name: Create DB for replication
  become_user: postgres
  become: yes
  postgresql_db:
    name: repmgr
    owner: repmgr
    encoding: 'UTF-8'
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'
    template: 'template0'
    state: present
  notify: restart postgresql-9.5

# - name: Set privileges for DB
#   become_user: postgres
#   become: yes
#   postgresql_privs:
#     db: repmgr
#     privs: ALL
#     type: database
#     role: repmgr
#     state: present
#   notify: restart postgresql-9.5

- name: Create repmgr path to config
  file:
    path: /var/lib/pgsql/repmgr/
    state: directory
    owner: postgres
    group: postgres
    #state: present
  notify: restart postgresql-9.5

- name: Create repmgr config
  template:
    src: roles/masterNode/templates/repmgr.conf.j2
    dest: /var/lib/pgsql/repmgr/repmgr.conf
    owner: postgres
    group: postgres

- name: restart postgresql-9.5
  service:
      name: postgresql-9.5
      state: restarted

- name: Checkin node as master server
  become_user: postgres
  become: yes
  command: /usr/pgsql-9.5/bin/repmgr -f repmgr.conf master register
  args:
    chdir: /var/lib/pgsql/repmgr/
