
- name: Create repmgr config ---  SLAVE DB
  template:
    src: roles/slaveNode/templates/repmgr.conf.j2
    dest: /var/lib/pgsql/repmgr/repmgr.conf
    owner: postgres
    group: postgres

- name: Copy existing data on the master ---  SLAVE DB
  become_user: postgres
  become: yes
  command: /usr/pgsql-9.5/bin/repmgr -h 192.168.33.100 -U repmgr -d repmgr -D /var/lib/pgsql/9.5/data/ -f /var/lib/pgsql/repmgr/repmgr.conf standby clone -F
  ignore_errors: yes
  notify: restart postgresql-9.5
  args:
    creates: /var/lib/pgsql/9.5/data/postgresql.conf

- name: Start PostgreSQL and enable at boot ---  SLAVE DB
  service:
    name: postgresql-9.5
    enabled: yes
    state: started

- name: Checkin node slave ---  SLAVE DB
  become_user: postgres
  become: yes
  command: /usr/pgsql-9.5/bin/repmgr -f /var/lib/pgsql/repmgr/repmgr.conf standby register
  args:
    chdir: /var/lib/pgsql/repmgr/
  ignore_errors: yes

