---
- name: Add repository ---  COMMON
  yum:
    state: present
    pkg: https://yum.postgresql.org/9.5/redhat/rhel-7.2-x86_64/pgdg-centos95-9.5-2.noarch.rpm

- name: PostgreSQL | Install PostgreSQL  ---  COMMON
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql95-server
    - postgresql95
    - postgresql95-libs
    - postgresql95-devel
    - postgresql95-contrib
    - python-psycopg2
    - https://yum.postgresql.org/9.5/redhat/rhel-7.2-x86_64/repmgr95-3.3.1-1.rhel7.x86_64.rpm

- name: Create repmgr path to config ---  COMMON
  file:
    path: /var/lib/pgsql/repmgr/
    state: directory
    owner: postgres
    group: postgres
  notify: restart postgresql-9.5

- name: Open port for postgres ---  COMMON
  firewalld:
      port: 5432/tcp
      permanent: true
      state: enabled
