---

#sudo: yes
- name: Add repository
  yum:
    state: present
    pkg: https://yum.postgresql.org/9.5/redhat/rhel-7.2-x86_64/pgdg-centos95-9.5-2.noarch.rpm

- name: PostgreSQL | Install PostgreSQL
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql95-server
    - postgresql95
    - postgresql95-libs
    - postgresql95-devel
    - postgresql95-contrib
    - python-psycopg2

- name: Initiate database
  command: /usr/pgsql-9.5/bin/postgresql95-setup initdb
  args:
      creates: /var/lib/pgsql/9.5/data/postgresql.conf

- name: Start PostgreSQL and enable at boot
  service:
      name: postgresql-9.5
      enabled: yes
      state: started

- name: Ensure PostgreSQL is listening on all localhost
  lineinfile:
      path: /var/lib/pgsql/9.5/data/postgresql.conf
      regexp: '^#?listen_addresses\s*='
      line: listen_addresses = '*'
      state: present
  notify:
  - restart postgresql-9.5

- name: Insert md5 connection type and  add  local connection
  lineinfile:
      path: /var/lib/pgsql/9.5/data/pg_hba.conf
      line: 'host  all  all  127.0.0.1/32  trust'
      line: 'host  all  all  0.0.0.0/0  md5' # chenge into production network
      insertafter: EOF
      state: present
  notify:
  - restart postgresql-9.5

- name: Open port for postgres
  firewalld:
      port: 5432/tcp
      permanent: true
      state: enabled
  notify: restart postgresql-9.5

- name: Create DB user
  become_user: postgres
  become: yes
  postgresql_user:
      name: omsuser
      password: omspasswd
      state: present
      encrypted: no
  notify: restart postgresql-9.5

- name: Create DB
  become_user: postgres
  become: yes
  postgresql_db:
      name: omsdb
      owner: omsuser
      encoding: 'UTF-8'
      lc_collate: 'en_US.UTF-8'
      lc_ctype: 'en_US.UTF-8'
      template: 'template0'
      state: present
  notify: restart postgresql-9.5

- name: Set privileges for DB
  become_user: postgres
  become: yes
  postgresql_privs:
      db: omsdb
      privs: ALL
      type: database
      role: omsuser
      state: present
  notify: restart postgresql-9.5

